### ISSUE TITLE
Incorrect formatting when the text is saved.

### ISSUE THREAD

**Issue by wf9a5m75** [shurcooL/atom-markdown-format#16]
Hi, this plugin is useful except the plugin breaks the format everything.

When I save the text file using [ctrl] + [s], this plugin formats the text file incorrectly.

https://www.youtube.com/watch?v=XOBZAXgdbII

**Comment by shurcooL** [comment]
Hi, can you please copy and paste the sample input Markdown into a gist.

https://gist.github.com/

That way I can test it and see what the issue is.

From the video, it's hard to tell, but maybe you're using one space for indenting lists? If so, you need to use at least two spaces or a tab character.

This won't work:

```Markdown
- One space is not okay.
 - Not okay.
```

But this will work:

```Markdown
- Two spaces or more, or tab are fine.
  - Two spaces okay.
```

**Comment by wf9a5m75** [comment]
Here is the example text:
https://gist.github.com/wf9a5m75/6131319cbd44417d4f5a

I reinstalled Atom, and only installed your plugin.
The problem occurs the file extension is `*.md` and the text includes two-bytes characters.
The file encode is UTF-8.

https://www.youtube.com/watch?v=qCZfGJSHpnU

**Comment by shurcooL** [comment]
> Here is the example text:
https://gist.github.com/wf9a5m75/6131319cbd44417d4f5a

The problem seems to be that you're not including a blank line between blocks. Markdown Format needs it.

See https://gist.github.com/shurcooL/2fe290f4fe804ec2fae9 for a fixed version, which gets formatted better (it doesn't change the rendered HTML result).

**Comment by wf9a5m75** [comment]
Github works without a blank line between blocks.

**Comment by shurcooL** [comment]
Yes, it does. I had to make a decision about how to handle "hard line" breaks, and I went with making blank lines between paragraphs/blocks mandatory.

The reason is the following. Markdown Format tries to fix formatting, and a part of that is to remove unneeded whitespace between words. For example, if you have two spaces by accident between two words, Markdown Format fixes that:

```
This is a  sentence with two spaces by accident.
```

It also joins a paragraph that was split up into multiple lines into a single paragraph, so:

```
This is
a paragraph
that will
 become a single line.
```

Becomes:

```
This is a paragraph that will become a single line.
```

That's why it thinks the line entry belongs as part of the previous sentence if you don't include an empty line break.

I suggest you either use a blank line to separate paragraphs and blocks, or avoid using Markdown Format. Its formatting is a certain way, and if you don't like it, unfortunately it's not customizable.

**Comment by wf9a5m75** [comment]
I see. How about insert a break line? That's normal formatter role (I
think).

**Comment by shurcooL** [comment]
One of the design goals is to convert paragraphs with manually added newlines, such as,

```
This is
a paragraph
that will
 become a single line.
```

Into paragraphs without newlines (to be wrapped automatically via word-wrap of your editor).

Because of that, inserting break lines is not really an option.

**Comment by wf9a5m75** [comment]
Ok, this is your plugin. You can choose the final answer.
Thanks for your help :)

**Comment by shurcooL** [comment]
No problem, thanks for reporting issue and sorry I couldn't help more.
