### ISSUE TITLE
deprecation notice / similar package

### ISSUE THREAD

**Issue by notslang** [shurcooL/atom-markdown-format#29]
Hey, I noticed your deprecation notice and wanted to reach out because I've been building a similar package called [tidy-markdown](https://github.com/slang800/atom-tidy-markdown) with the same goal of a [canonical markdown format](https://github.com/slang800/markdown-styleguide), like gofmt.

I've actually run into many of the same issues as you... I started with rather basic processing & formatting of the marked ast, gradually found special cases like yaml front matter & fixed them... And recently decided to switch to an html-based ast (from parse5) to make it easier to convert chunks of html in the markdown and switch between markdown parsers if I find something better than marked.

My codebase is all in CoffeeScript rather than Go, but I'd love to work together since we have such similar projects. Or at least I could provide an upgrade path so people have something to switch to when your package is removed.

**Comment by dmitshur** [comment]
Hi @slang800,

Thanks for reaching out and letting me know. We've definitely started out with similar motivations and traversed similar paths. :)

You should see the reasons I decided to deprecate this package in the first place:

>  My initial plan was to make `markdownfmt` essentially perfect, the way `gofmt` is, so that it could be always run-on-save in every possible situation, without needing for configuration or to ever turn it off. ... Along the way, I learned there are many obstacles that prevent from that being possible with Markdown (without doing an exorbitant amount of work). ... With my very limited resources, I can't develop and maintain it further.

I basically gave up on my original goal (making a perfect formatter for Markdown) because I learned/deemed it essentially an impossible task.

I may want to come back to this initiative sometime in the future, but if I pick this up, I would have to invent a new type of Markdown and be very opinionated about it. But that has problems of its own (hard to get adoption now, and hard to come up with something simple and good), which is why this is not high on my priorities list.

> Or at least I could provide an upgrade path so people have something to switch to when your package is removed.

I'm happy to link to your project under a list of alternatives, either here, or at https://github.com/shurcooL/markdownfmt#alternatives.

Just one more note. I am still supporting and working on [`markdownfmt`](https://github.com/shurcooL/markdownfmt), a Go library and command that this package was a wrapper around, because I find its smaller scope is easier to support and provide a good experience with. I rely on it myself.

**Comment by notslang** [comment]
> You should see the reasons I decided to deprecate this package in the first place

Yep, I read through those, and right now I'm happy to do an "exorbitant amount of work" :wink:.

> I'm happy to link to your project under a list of alternatives...

Thanks, I'll be sure to send a PR & (since you're continuing markdownfmt), I'll do the same on my readme.
