### ISSUE TITLE
Force replace '_' when write latex equations on save

### ISSUE THREAD

**Issue by Alienfeel** [shurcooL/atom-markdown-format#31]
like $p_i=1-err/tot$ would be transfered as $p*i=1-err/tot$

**Comment by dmitshur** [comment]
I am sorry, but I'm unable to provide support on this deprecated package (see https://github.com/shurcooL-legacy/atom-markdown-format#deprecation-notice, and it's also under shurcooL-legacy namespace).

The issue is that `markdownfmt`, which atom-markdown-format is a wrapper around, does not support LaTeX extension, so it treats the above as normal text.

My suggestion is to not use `atom-markdown-format` on Markdown documents that depend on LaTeX extension.

**Comment by Alienfeel** [comment]
I am so sorry to hear that
