### ISSUE TITLE
Linebreaks go away.

### ISSUE THREAD

**Issue by alex-kovac** [shurcooL/atom-markdown-format#8]
Hi, Nice work with this package! Please forgive my insolence but this useful part of Markdown syntax is not preserved it seems:  "When you do want to insert a <br /> break tag using Markdown, you end a line with two or more spaces, then type return."

**Comment by bradharms** [comment]
Hi, I wanted to comment on this to ask a question before requesting a new feature.

I would like a setting to enable an alternate formatting mode where paragraphs with too-long lines and too-short lines will be normalized to fit into the current max columns setting in Atom in the same
way as the `Ctrl-Alt-Q` shortcut, but only for paragraphs and not tables, code listings, really long links, etc. The current behavior is that all lines in a paragraph are concatenated into a single line no matter what.

This feature would have no affect on the output but it would be very useful when editing pages that have deeply-nested code or very wide tables, because, with soft wrap turned off, you would be able to see paragraphs wrapped and wide listings not wrapped.

**Comment by shurcooL** [comment]
Why not just enable word wrap? Is it because your code and tables are too wide to fit and get wrapped also?

**Comment by bradharms** [comment]
Yes, that's main main reason
